//! Factory tooling setup for cas init
//!
//! Creates lightweight worktree helper templates managed by CAS.

use anyhow::Result;
use std::path::Path;

/// Create .env.worktree.template
pub fn create_env_template(cwd: &Path) -> Result<bool> {
    let template_path = cwd.join(".env.worktree.template");

    if template_path.exists() {
        return Ok(false);
    }

    let content = r#"# Worktree environment template
# Generated by: cas worktree create
# Copy to .env.worktree and customize per worktree
#
# SLOT is assigned automatically by cas worktree create
# Use it to derive unique ports for this worktree

# Assigned worktree slot (do not edit)
SLOT={{SLOT}}

# Supervisor: define your port scheme below
# Example port offsets (SLOT * 10):
#
# WEB_PORT=$((3000 + ($SLOT * 10)))
# API_PORT=$((8080 + ($SLOT * 10)))
# DB_PORT=$((5432 + ($SLOT * 10)))
#
# Or use database name isolation (shared postgres):
# DATABASE_NAME=myapp_slot${SLOT}
#
# iOS Simulator UDID (assigned by supervisor or cas worktree create)
# SIM_UDID=

# Add your service-specific env vars below:
"#;

    std::fs::write(&template_path, content)?;
    Ok(true)
}

/// Create scripts/worktree-boot.sh
pub fn create_boot_script(cwd: &Path) -> Result<bool> {
    let scripts_dir = cwd.join("scripts");
    let script_path = scripts_dir.join("worktree-boot.sh");

    if script_path.exists() {
        return Ok(false);
    }

    std::fs::create_dir_all(&scripts_dir)?;

    let content = r#"#!/usr/bin/env bash
# Worktree boot script
# Generated by: cas init
#
# Usage: ./scripts/worktree-boot.sh [slot]
#
# This script:
# 1. Generates .env.worktree from template with assigned SLOT
# 2. Exports the variables for subsequent commands in this shell

set -euo pipefail

SLOT="${1:-1}"
TEMPLATE=".env.worktree.template"
OUTPUT=".env.worktree"

# Generate .env.worktree from template
if [[ -f "$TEMPLATE" ]]; then
    sed "s/{{SLOT}}/$SLOT/g" "$TEMPLATE" > "$OUTPUT"
    echo "Generated $OUTPUT with SLOT=$SLOT"
else
    echo "Warning: $TEMPLATE not found, skipping env generation"
fi

# Source the generated env
if [[ -f "$OUTPUT" ]]; then
    set -a
    source "$OUTPUT"
    set +a
fi

echo "Environment prepared from $OUTPUT"
echo "Run your project-specific dev command next."
"#;

    std::fs::write(&script_path, content)?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&script_path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&script_path, perms)?;
    }

    Ok(true)
}

/// Update .gitignore with worktree-specific files
pub fn update_gitignore(cwd: &Path) -> Result<bool> {
    let gitignore_path = cwd.join(".gitignore");

    let entries = vec![
        "# Worktree-specific files (generated per worktree)",
        ".env.worktree",
        "# fallow incremental analysis cache (used by the fallow skill)",
        ".fallow/",
    ];

    let mut content = if gitignore_path.exists() {
        std::fs::read_to_string(&gitignore_path)?
    } else {
        String::new()
    };

    let mut modified = false;
    for entry in entries {
        if !content.contains(entry) {
            if !content.is_empty() && !content.ends_with('\n') {
                content.push('\n');
            }
            content.push_str(entry);
            content.push('\n');
            modified = true;
        }
    }

    if modified {
        std::fs::write(&gitignore_path, content)?;
    }

    Ok(modified)
}

/// Full factory tooling setup
/// Returns a summary string of what was done
pub fn setup_factory_tooling(cwd: &Path) -> Result<String> {
    if std::env::var("CAS_SKIP_FACTORY_TOOLING").ok().as_deref() == Some("1") {
        return Ok("skipped".to_string());
    }

    let mut results = Vec::new();

    // Create CAS-managed helper templates only.

    if create_env_template(cwd)? {
        results.push(".env.worktree.template");
    }

    if create_boot_script(cwd)? {
        results.push("scripts/worktree-boot.sh");
    }

    if update_gitignore(cwd)? {
        results.push(".gitignore updated");
    }

    if results.is_empty() {
        Ok("already configured".to_string())
    } else {
        Ok(results.join(", "))
    }
}
