#!/usr/bin/env bash
# Worktree boot script
# Generated by: cas init
#
# Usage: ./scripts/worktree-boot.sh [slot]
#
# This script:
# 1. Generates .env.worktree from template with assigned SLOT
# 2. Starts services via overmind

set -euo pipefail

SLOT="${1:-1}"
TEMPLATE=".env.worktree.template"
OUTPUT=".env.worktree"

# Generate .env.worktree from template
if [[ -f "$TEMPLATE" ]]; then
    sed "s/{{SLOT}}/$SLOT/g" "$TEMPLATE" > "$OUTPUT"
    echo "Generated $OUTPUT with SLOT=$SLOT"
else
    echo "Warning: $TEMPLATE not found, skipping env generation"
fi

# Source the generated env
if [[ -f "$OUTPUT" ]]; then
    set -a
    source "$OUTPUT"
    set +a
fi

# Start services
echo "Starting services with mise run dev..."
mise run dev
